# Generated by Django 6.0.7 on 2026-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio en Guaraníes')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del Producto')),
            ],
        ),
    ]
